### ISSUE TITLE
veins-gym for multiple processes/ agents 

### ISSUE THREAD

**Issue by lionyouko** [tkn-tub/veins-gym#5]
Hi,
In order to use veins-gym framework with federated learning, I was thinking about how to make it run with multiple instances of openAI environments. I going to start to work on this but, since it is not the major part of my thesis, I may try to find the easiest working solution for now. 

What I need is to have different, separated working instances of agents, and therefore, it seems that I need different GymConnection modules working in parallel each of them connected to a different port.

I was also thinking how I could separate the configuration part from the learning part itself, as, for now, the tool receives a certain message that means configuration.

If you have any suggestion regarding this, I will be very glad to think about how I could make it.
Thank you very much.

**Comment by lionyouko** [comment]
Yes, the most important aspect is:

I not only need multiple veinsgym agents, but all of them linked to a specific running simulation (specific process). 

But the reset function could kill the simulation process and let the other agents to starve.

I need to find a way that before reseting, all agents are actually done with their parts. For example, after an episode to finish, before to start another simulation process, the agent waits the other agents to be done. 

It is important to be able to communicate with the current process that has sockets open with zmq in certain ports. That is easier to do. Each gymConnection will open a socket in 127.0.0.1:<port> in which the port may be given by 5000 + number given omnetpp.ini for that gymConnection or its position in a vector of connectors, for example. Since I am thinking into having another program python process launching these agents, it is okay. 

If you have any suggestion, please, tell me. Thank you.

**Comment by dbuse** [comment]
Hi @lionyouko 

to clarify on your requirements: You want multiple agents connected to the same simulation and thus the same environment. Did I get that right?

If so, I would suggest leaving the GymConnection and its equivalent in the VeinsGym Python code as-is and only changing the parts that interact with them on the outside.
On the Python/Agent side, this could be done by wrapping the environment object in a class that is able to talk to a collection of proxy environments. Each agent would get its proxy environment, which in turn communicates with the wrapper environment. The proxies would behave like normal environments to their agents, delivering observations and rewards specific to the agent to them and collecting actions from their agent. The wrapper would receive observations and rewards for *all* agents and distribute them to the proxies, while also collecting actions from all agents (through the proxies) and feed them to the simulation through the original VeinsGym environment object. So the synchronization (if needed) between agents could be implemented in Python. This could lead to some blocking time, but only where semantically necessary. If necessary, this could even be distributed across a network.

On the Simulation/C++ side, you would need to distribute actions from the GymConnection to the Vehicles/Applications/Modules which perform the actions selected by the agents.

I hope this helps.

**Comment by lionyouko** [comment]
You very kind, Dr. Dbuse. I am taking your ideas in consideration.
Thank You very much

**Comment by dbuse** [comment]
Great.
I'll close this issue for now.
